name: moco
recipe: drupal9
config:
  php: '7.4'
  webroot: web
  composer_version: 2.0.7
  via: apache
  database: mysql
  config:
    php: config/php.ini
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'https://moco.lndo.site'
tooling:
  drush:
    cmd: /app/vendor/drush/drush/drush
