import './components/alert-error'
import './components/main-slider'
import './components/producto-destacado-slider'
import './components/menu'
import './components/quiz-options'
import './components/traslate'
import './test/test'
import './test/aid'
